<?php
// auto-generated by sfPropelCrud
// date: 02/24/2006 18:23:49
?>
<h1>User</h1>

<table>
<thead>
<tr>
  <th>User</th>
  <th>User nm</th>
  <th>User pswd</th>
  <th>User email</th>
  <th>Auth lvl</th>
  <th>Created at</th>
  <th>Updated at</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
    <td><?php echo link_to($user->getUserId(), 'User/show?user_id='.$user->getUserId()) ?></td>
      <td><?php echo $user->getUserNm() ?></td>
      <td><?php echo $user->getUserPswd() ?></td>
      <td><?php echo $user->getUserEmail() ?></td>
      <td><?php echo $user->getAuthLvlId() ?></td>
      <td><?php echo $user->getCreatedAt() ?></td>
      <td><?php echo $user->getUpdatedAt() ?></td>
  </tr>
<?php endforeach ?>
</tbody>
</table>

<?php echo link_to ('create', 'User/edit') ?>
